namespace Twinfield_NewFramework
{
    public enum TwinfieldDBTenant
    {
        A,
        B,
        C,
        D,
        E,
    }

    public enum TwinfieldScenarioName
    {
        CreateInvoice,
        EditInvoice,
        ExtendedTBReport,
        NeoFixedAsset,
        NeoSalesInvoices,
        ClassicSalesInvoices,
        CreateTransaction,
        ReadTransaction,
        CompanySettings,
        UserAccessSettings,
        DocumentManagement,
        PayAndCollectRun,
        ExportCustomers,
    }
    public enum SpecificScenarioName
    {
        CreateInvoice_A,
        CreateInvoice_B,
        CreateInvoice_C,
        CreateInvoice_D,
        CreateInvoice_E,        
        CompanySettings_A,
        CompanySettings_B,
        CompanySettings_C,
        CompanySettings_D,
        CompanySettings_E,
        ExtendedTBReport_A,
        ExtendedTBReport_B,
        ExtendedTBReport_C,
        ExtendedTBReport_D,
        ExtendedTBReport_E,
        NeoFixedAsset_A,
        NeoFixedAsset_B,
        NeoFixedAsset_C,
        NeoFixedAsset_D,
        NeoFixedAsset_E,
        NeoSalesInvoices_A,
        NeoSalesInvoices_B,
        NeoSalesInvoices_C,
        NeoSalesInvoices_D,
        NeoSalesInvoices_E,
        ClassicSalesInvoices_A,
        ClassicSalesInvoices_B,
        ClassicSalesInvoices_C,
        ClassicSalesInvoices_D,
        ClassicSalesInvoices_E,
        CreateTransaction_A,
        CreateTransaction_B,
        CreateTransaction_C,
        CreateTransaction_D,
        CreateTransaction_E,
        ReadTransaction_A,
        ReadTransaction_B,
        ReadTransaction_C,
        ReadTransaction_D,
        ReadTransaction_E,
        UserAccessSettings_A,
        UserAccessSettings_B,
        UserAccessSettings_C,
        UserAccessSettings_D,
        UserAccessSettings_E,
        DocumentManagement_A,
        DocumentManagement_B,
        DocumentManagement_C,
        DocumentManagement_D,
        DocumentManagement_E,
        PayAndCollectRun_A,
        PayAndCollectRun_B,
        PayAndCollectRun_C,
        PayAndCollectRun_D,
        PayAndCollectRun_E,
        ExportCustomers_A,
        ExportCustomers_B,
        ExportCustomers_C,
        ExportCustomers_D,
        ExportCustomers_E,
        EditInvoice,
    }

 //   public enum TwinfieldInputData
	//{
 //       CreateInvoice,
 //       EditInvoice,
 //       CompanySettings,
 //   }
    public enum TwinfieldScenarioPrefix
    {
        CI_,
        EI_,
        CS_,
        ETBR_,
        NFA_,
        NSI_,
        CSI_,
        CT_,
        RT_,
        UAS_,
        DM_,
        PCR_,
        EC_,
    }

}